export const ListaProizvoda = [
    {id: 1, naziv: 'Moja Kafica Select', alias: 'select', kategorija: 'Tradicionalna kafa',  tekst: 'Moja Kafica Select je specijalna kafa premium kvaliteta. Napravljena je od mešavine najvalitetnije Arabica kafe.', pakovanje: '100g / 200g / 500g'},
    {id: 2, naziv: 'Moja Kafica Select sa kutijom', alias: 'selectsakutijom', kategorija: 'Tradicionalna kafa',  tekst: 'Moja Kafica Select je specijalna kafa premium kvaliteta. Napravljena je od mešavine najvalitetnije Arabica kafe. Upakovana u luksuznu kartonsku kutiju. Idealna za poklon.', pakovanje: '200g'},
    {id: 3, naziv: 'Moja Kafica Select Arabica sa kutijom', alias: 'selectarabica', kategorija: 'Tradicionalna kafa',  tekst: 'Moja Kafica Select Arabica je specijalna kafa premium kvaliteta. Napravljena je od mešavine najvalitetnije Arabica kafe. Upakovana u luksuznu kartonsku kutiju. Idealna za poklon.', pakovanje: '200g'},
    {id: 4, naziv: 'Moja Kafica domaća kafa', alias: 'domacakafa', kategorija: 'Tradicionalna kafa',  tekst: 'Moja Kafica domaća kafa mešavina je pažljivo odabranih vrsta kafa arabike i robuste, obogaćena sa 20% surogata.', pakovanje: '100g / 200g / 500g'},
    {id: 5, naziv: 'Moja Kafica Domaća kafa', alias: 'instantdomacakafa', kategorija: 'Instant kafa',  tekst: 'Moja Kafica Domaća kafa je pravi izbor za sve one koji žele pravu domaću kafu brzo i lako spremljenu.', pakovanje: '8g / Zbirno pakovanje od 30x8g'},
    {id: 6, naziv: 'Moja Kafica Domaća kafa + šećer', alias: 'instantdomacakafasecer', kategorija: 'Instant kafa',  tekst: 'Moja Kafica Domaća kafa je pravi izbor za sve one koji žele pravu domaću kafu brzo i lako spremljenu.', pakovanje: '8g / Zbirno pakovanje od 30x8g'},
    {id: 7, naziv: 'Moja Kafica Domaća kafa + mleko', alias: 'instantdomacakafamleko', kategorija: 'Instant kafa',  tekst: 'Moja Kafica Domaća kafa je pravi izbor za sve one koji žele pravu domaću kafu brzo i lako spremljenu.', pakovanje: '8g / Zbirno pakovanje od 30x8g'},
    {id: 8, naziv: 'Moja Kafica 2u1 klasik', alias: '2u1', kategorija: 'Instant kafa',  tekst: 'Moja Kafica 2u1 klasik je instant kafa proizvedena po visokim standardima, laka i brza priprema.', pakovanje: '12g / Zbirno pakovanje od 25x12g'},
    {id: 9, naziv: 'Moja Kafica 3u1 klasik', alias: '3u1', kategorija: 'Instant kafa',  tekst: 'Moja Kafica 3u1 klasik je instant kafa proizvedena po visokim standardima, laka i brza priprema.', pakovanje: '17g / Zbirno pakovanje od 25x17g'}
]